config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'admin/show_menu' => 'admin#show_menu', as: :admin_show_menu

  patch 'admin/edit' => 'admin#edit', as: :save_menu_item_changes
    
  post 'admin/create' => 'admin#create', as: :create_menu_item

  get 'admin/show_item' => 'admin#show_item', as: :admin_show_item

  get 'admin/new_item' => 'admin#new', as: :create_new_item    
    
  get 'main/index' => 'main#index', as: :index

  get 'main/about'

  get 'main/contacts'
    
  get 'main/placeholder' => 'main#placeholder', as: :placeholder    

   root 'main#placeholder'

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
     
  def new
    @sub_sections = MenuItem.where(:section => params[:section]).uniq.pluck(:second_section)
    @item = MenuItem.new
    @item.section = params[:section]
  end  
    
  def create
      params.require(:menu_item).permit!
      @item = MenuItem.new
      @item.update(params[:menu_item])
      if @item.save
        redirect_to admin_show_menu_path
      else
        render admin_show_item_path
      end  
  end      
    
  def index
  end

  def show_menu
       res = {}
      MenuItem.uniq.pluck(:section).each do |section_title|
           puts section_title
           section = Section.new section_title
           section.second_sections = []
           MenuItem.where(section: section_title).uniq.pluck(:second_section).each do |second_section_title|
               puts second_section_title
               second_section = SecondSection.new(second_section_title)
               second_section.items = []
               MenuItem.where("section = ? AND second_section = ?", section_title, second_section_title).each do |item|
                   puts item.name
                   second_section.items << item
               end   
               section.second_sections << second_section
           end       
           res[section.section_name] = section           
      end      
          
      @res = res
  end

  def edit
      params.require(:menu_item).permit!
      @item = MenuItem.find(params[:menu_item][:id])
      @item.update(params[:menu_item])
      if @item.save
        redirect_to admin_show_menu_path
      else
        render admin_show_item_path
      end      
  end

  def show_item
      @item = MenuItem.find(params[:item_id])
      @sub_sections = MenuItem.where(:section => @item.section).uniq.pluck(:second_section)
  end
    
       class SecondSection
        attr_accessor :items, :second_section_name 
        def initialize(second_section_name)
            self.second_section_name = second_section_name
        end
    end    

    class Section
        attr_accessor :second_sections, :section_name 
        def initialize(section_name)
            self.section_name = section_name
        end
    end   
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
   http_basic_authenticate_with name: "regopizza", password: "password", except: :placeholder
   
  def placeholder 
      render :layout => false
  end      
      
  def index       
      res = {}
      MenuItem.uniq.pluck(:section).each do |section_title|
           puts section_title
           section = Section.new section_title
           section.second_sections = []
           MenuItem.where(section: section_title).uniq.pluck(:second_section).each do |second_section_title|
               puts second_section_title
               second_section = SecondSection.new(second_section_title)
               second_section.items = []
               MenuItem.where("section = ? AND second_section = ?", section_title, second_section_title).each do |item|
                   puts item.name
                   second_section.items << item
               end   
               section.second_sections << second_section
           end       
           res[section.section_name] = section           
      end      
          
      @res = res
  end

  def about
  end

  def contacts
  end

    class SecondSection
        attr_accessor :items, :second_section_name 
        def initialize(second_section_name)
            self.second_section_name = second_section_name
        end
    end    

    class Section
        attr_accessor :second_sections, :section_name 
        def initialize(section_name)
            self.section_name = section_name
        end
    end       

end


 

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/edit.html.erb
<h1>Admin#edit</h1>
<p>Find me in app/views/admin/edit.html.erb</p>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/new.erb
<%= simple_form_for(@item, html: { class: 'form-horizontal' }, :url => create_menu_item_path) do |f| %>

<br>
<br>
<br>
<br>

<div class="row">
<div class="col-xs-10 col-xs-offset-1">
<div class="panel panel-primary">
 <div class="panel-heading">
     <h3>Change Menu Item </h3>
     <h4><%= " - Category: #{@item.section}" %></h4>
 </div>
  <div class="panel-body">
     <div class="col-xs-10 col-xs-offset-1">
     
      
      <%= f.input :second_section, label: 'Sub-category', collection: @sub_sections, prompt: "Select your age", selected: 21 %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :extras %>
      <%= f.input :price %>
      <%= f.input :section, :as => :hidden %>
      <%= f.input :id, :as => :hidden %>
      
      
      <hr>
      <h5>Hot to:</h5>
      <img src="/menu_item_tutorial.jpg" alt="" class="img-responsove">
      <hr>
      
      <%= f.button :submit, class: "pull-right btn-primary"%>
  
      
      </div>
  </div>
</div>
</div>
  </div>


<% end %>

app/views/admin/show_item.html.erb
<%= simple_form_for(@item, html: { class: 'form-horizontal' }, :url => save_menu_item_changes_path) do |f| %>

<br>
<br>
<br>
<br>

<div class="row">
<div class="col-xs-10 col-xs-offset-1">
<div class="panel panel-primary">
 <div class="panel-heading">
     <h3>Change Menu Item </h3>
     <h4><%= " - Category: #{@item.section}" %></h4>
 </div>
  <div class="panel-body">
     <div class="col-xs-10 col-xs-offset-1">
     
      
      <%= f.input :second_section, label: 'Sub-category', collection: @sub_sections, prompt: "Select your age", selected: @item.second_section %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :extras %>
      <%= f.input :price %>
      <%= f.input :section, :as => :hidden %>
      <%= f.input :id, :as => :hidden %>
      
      
      <hr>
      <h5>Hot to:</h5>
      <img src="/menu_item_tutorial.jpg" alt="" class="img-responsove">
      <hr>
      
      <%= f.button :submit, class: "pull-right btn-primary"%>
  
      
      </div>
  </div>
</div>
</div>
  </div>


<% end %>

app/views/admin/show_menu.html.erb
<div class="row">
    
           <div class="row">                                
            <div class="col-sm-12 col-md-4 white-col">
              <%= render :partial => '/layouts/menu_chunk_admin', :locals => {:menu_item => @res["BREAKFAST MENU"] } %>
             <%= render :partial => '/layouts/menu_chunk_admin', :locals => {:menu_item => @res["HOT BEVARAGES"] } %>
            </div>
            <div class="col-sm-12 col-md-4 brown-col">
                 <%= render :partial => '/layouts/menu_chunk_admin', :locals => {:menu_item => @res["LUNCH/DINNER MENU"] } %>
            </div>
            <div class="col-sm-12 col-md-4 white-col">
              <%= render :partial => '/layouts/menu_chunk_admin', :locals => {:menu_item => @res["PIZZA MENU"] } %>
              <%= render :partial => '/layouts/menu_chunk_admin', :locals => {:menu_item => @res["COLD BEVARAGES"] } %>
            </div> 
            </div>
    
</div>

app/views/layouts/_footer.haml
%hr
%footer.footer-distributed
  .footer-left
    %h3
      Regopiza.com
    %p.footer-links
      = link_to "Home", root_path
      ·
      = link_to "About", root_path
      ·
      = link_to 'Contacts', root_path
    %p.footer-company-name regopizza.com © 2017
  .footer-center
    %div
      %i.fa.fa-map-marker
      %p
        %a{:href => "https://www.google.com/maps/dir/Current+Location/1215+Bay+Street+Staten+Island+NY+10305"}
          %span 91-16 63rd Drive
          Rego Park, NY 11374
    %div
      %i.fa.fa-phone
      %p
        %a{:href => "tel:+1-718-406-9111"} 718.406.9111
  .footer-right
    %p.footer-company-about
      %span regopizza.com
      some description
    .footer-icons
      %a{:href => "#"}
        %i.fa.fa-facebook
      %a{:href => "#"}
        %i.fa.fa-google-plus
      %a{:href => "#"}
        %i.fa.fa-instagram
      %a{:href => "#"}
        %i.fa.fa-twitter

app/views/layouts/_menu_chunk.erb
        <% unless menu_item.nil? %>
            <div class="menu-body" id="<%= anchor_link %> ">
                 <!-- Section starts: Appetizers -->
                 <div class="menu-section">
                  <div class="row title-parent">
                       <div class="col-xs-10">
                          <h2 class="menu-section-title"><%= menu_item.section_name %></h2>
                       </div>
                       <div class="col-xs-2 menu-section-title title-child">
                           
                       </div>
                  </div>
                    <!-- Section second title -->
                    <% menu_item.second_sections.each do |second_section| %>
                    <div>
                        <h3 class="menu-section-second-title">
                            <%= second_section.second_section_name %>
                        </h3>
                    </div>
                    
                    <% second_section.items.each do |item| %>
                    
                    <!-- Item starts -->
                    <div class="menu-item">
                       <div class="menu-item-name">
                         <%= item.name %>
                       </div>
                       <div class="menu-item-price">
                         <%= item.price %>
                       </div>
                       <div class="menu-item-description">
                         <% unless item.description.nil? || item.description.empty? %>
                             <span><%= item.description %> </span>
                         <% end %>
                         <% unless item.extras.nil? || item.extras.empty? %>
                           <br>
                           <span class="menu-extra"><%= item.extras %> </span>
                         <% end %>
                       </div>
                    </div>
                    <% end %>
                  <% end %>   
                  
                     <br>
                          <br>
                           
                 </div>
                 <!-- Section ends -->
              </div>
              <% end %>

app/views/layouts/_menu_chunk_admin.erb
        <% unless menu_item.nil? %>
            <div class="menu-body">
                 <!-- Section starts: Appetizers -->
                 <div class="menu-section">
                  <div class="row title-parent">
                       <div class="col-xs-10">
                          <h2 class="menu-section-title"><%= menu_item.section_name %></h2>
                       </div>
                       
                       <div class="col-xs-2 menu-section-title title-child">
                           
                       </div>
                  </div>
                   
                   <h6><%= link_to "Add new item >>>", create_new_item_path(:section => menu_item.section_name) %></h6>
                   
                    <!-- Section second title -->
                    <% menu_item.second_sections.each do |second_section| %>
                    <div>
                        <h3 class="menu-section-second-title">
                            <%= second_section.second_section_name %>
                        </h3>
                    </div>
                    
                    <% second_section.items.each do |item| %>

                    <!-- Item starts -->
                    <div class="menu-item admin-menu-item">
                       <div class="menu-item-name">
                         <%= link_to item.name, admin_show_item_path(item_id: item.id) %>
                       </div>
                       <div class="menu-item-price">
                         <%= link_to item.price, admin_show_item_path(item_id: item.id) %> 
                       </div>
                       <div class="menu-item-description">
                         <% unless item.description.nil? || item.description.empty? %>
                             <span> <%= link_to item.description, admin_show_item_path(item_id: item.id) %> </span>
                         <% end %>
                         <% unless item.extras.nil? || item.extras.empty? %>
                           <br>
                           <span class="menu-extra"><%= link_to item.extras, admin_show_item_path(item_id: item.id) %> </span>
                          <% end %>
                        
                       </div>
                    </div>
                    <% end %>
                  <% end %>   
                  
                     <br>
                          <br>
                           
                 </div>
                 <!-- Section ends -->
              </div>
              <% end %>

app/views/layouts/_navbar.erb
<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed hidden" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RegoPizza.com</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav hidden">
            <li class="active"><a href="javascript:void(0);" id="nav-pizza-btn">Pizza Menu</a></li>
            <li><a href="#breakfast-menu">Breakfast Menu</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="tel:+1-718-406-9111">718.406.9111</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<a href="tel:+1-718-406-9111" class="visible-xs">   
<div class="call-btn-wrapper">
    ORDER NOW
</div>
<div class="call-btn">
   <span class="fa fa-phone"></span>
</div>   
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>RegoPizza.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="/css/style.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="/css/font-awesome.css">
 <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
</head>
<body>

<div class="container-fluid">
   <div class="row">
    <%= render "/layouts/navbar" %>
    </div>
    <%= yield %>
</div>
</body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/contacts.html.erb
<h1>Main#contacts</h1>
<p>Find me in app/views/main/contacts.html.erb</p>

app/views/main/index.html.erb
        
        <div class="row hidden-xs">
            <div class="col-sm-12 landing-wrapper">
                <div class="landing-part">
                    <div class="row">
                       <div class="col-sm-8 col-sm-offset-2">
                        <div class="col-sm-6 col-sm-offset-3 image-wrapper">
                            <img src="/img/logo.jpg" alt="rego-pizza center" class="img-responsive center">
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="row">
                  <div class="col-sm-4 col-sm-offset-4 ">
                    <br>
                     <div class="kosher-title">
                          <h4>UNDER STRICT KOSHER <br> SUPERVISION OF</h4>
                          <img src="/img/kosher-logo.png" alt="" class="ing-responsive">

                      </div>       
                  </div>
                </div>
                    </div>
                </div>
            </div>
        </div>

        
          
          <div class="row visible-xs">         
            <div class="col-xs-12 col-sm-12 col-md-4">
               <img src="/img/logo.jpg" alt="rego-pizza center" class="img-responsive center">
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4">
                <div class="row">
                  <div class="col-xs-12">
                     <br>
                      <div class="slogan">
                          <h3>
                              All Our Pizzas Are Made With Quality Ingredients Wth No MSG Added
                          </h3>
                      </div>
                      <div class="ads">
                          <h3>CATER YOUR NEXT EVENT WITH US</h3>
                          <h5>ASK ABOUT OUR CATERING SEVRICES</h5>
                      </div>
                      
                      
                    <br>
                     <div class="kosher-title kosher-border">
                          <h4>UNDER STRICT KOSHER <br> SUPERVISION OF</h4>
                          <div class="row">
                          <div class="col-xs-8 col-xs-offset-2">
                              <img src="/img/kosher-logo.png" alt="" class="ing-responsive">
                          </div>
                          </div>
                      </div>   
                      
                          <br>    
                
                      
                       <div class="delivery">
                          <h3>FREE FAST DELIVERY</h3>
                       </div>
                       
                       <div class="address">
                          <h3>91-16 63RD DRIVE, <br> REGO PARK, NY, 13374</h3>
                       </div>
                       
                  </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4">
               <div class="map-view">
                <iframe align="center" frameborder="0" height="350" src="https://www.google.com/maps/embed/v1/place?q=91-16%2063RD%Drive%2C%20Rego%20Park%2C%20NY%2C%20United%20States%2011374&amp;key=AIzaSyAG1JHhDDpKIublp2o1A107YHnRFEGQa7E" style="border:0" width="100%"></iframe>
                </div>
            </div>
            
        </div>

           <div class="row">                                
            <div class="col-xs-12 col-md-4 white-col">
              <%= render :partial => '/layouts/menu_chunk', :locals => {:menu_item => @res["BREAKFAST MENU"] , :anchor_link => "breakfast-menu"} %>
             <%= render :partial => '/layouts/menu_chunk', :locals => {:menu_item => @res["HOT BEVARAGES"] ,:anchor_link => "hot-bavarages-menu"} %>
            </div>
            <div class="col-xs-12 col-md-4 brown-col">
                 <%= render :partial => '/layouts/menu_chunk', :locals => {:menu_item => @res["LUNCH/DINNER MENU"], :anchor_link => "lunch-dinner-menu" } %>
            </div>
            <div class="col-xs-12 col-md-4 white-col">
              <%= render :partial => '/layouts/menu_chunk', :locals => {:menu_item => @res["PIZZA MENU"], :anchor_link => "pizza-menu" } %>
              <%= render :partial => '/layouts/menu_chunk', :locals => {:menu_item => @res["COLD BEVARAGES"], :anchor_link => "cold-bavarages-menu" } %>
            </div> 
            </div>
    
      <div class="row">
    <%= render "/layouts/footer" %>
</div> 
  

app/views/main/placeholder.erb
    
    <head>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    </head>
    
    <%= link_to 'admin access', index_path%>
    
    <div class="placeholder">
       <h1>Rego Pizza Website</h1>
       <h2>Coming soon... :)</h2>
        <img src="placeholder-img.jpeg" alt="">
    </div>
    
    